#!/bin/sh

TOOLS=$(dirname $0)

. ${TOOLS}/shell_utils

#
# Start
#

check_vars ROOT_PROJ TARGET_DIR TARG CYCLADES_FILES SYSTEM_DIR

check_dirs $ROOT_PROJ $SYSTEM_DIR $TARGET_DIR

check_files $ROOT_PROJ/$CYCLADES_FILES

cd $SYSTEM_DIR || exit -1

result=0

while read mode owner group file save
do
	if [ -d $file ]
	then
		install -d -m $mode $TARGET_DIR/$file || exit -1
	else
		if [ -f $file.$TARG ] ; then
			FILE="$file.$TARG"
		else
			FILE="$file"
		fi
		: ${save:="$file"}
		if [ -f $FILE ] ; then
		  install -D -m $mode $FILE $TARGET_DIR/$save || exit -1
		else
		  echo "ERROR: '$FILE' does not exist."
		  result=-1
		fi
	fi
done << -EOF
$(< $ROOT_PROJ/$CYCLADES_FILES)
-EOF

exit $result

