#!/bin/sh

cd /etc/hotplug
. ./cardmgr.functions

PCCARDCTL="/sbin/pccardctl"

prg_name="${0##*/}"

usage ()
{
	echo "usage: $prg_name command [socket #]"
	echo "    or $prg_name [-c configpath] [-f scheme] [-s stab] scheme [name]"
	echo "    commands: status config ident suspend resume reset eject insert"
	exit 2
}

#
# Find out whether hotplug is running. It takes always about 1 second to run.
#
hotplug_running ()
{
	if [ -n "$(ps -e | grep '/sbin/hotplug' | grep -v grep)" ]; then
		sleep 1
		return 0
	fi
	sleep 1
	# Confirmation after 1 second:
	if [ -n "$(ps -e | grep '/sbin/hotplug' | grep -v grep)" ]; then
		return 0
	fi

	return 1
}

wait_hotplug_events ()
{
	# TODO: Consider the use of udev in order to guarantee the event
	# ordering instead of using hotplug which makes no guarantees.
	local i
	for ((i=0; i<35; i++)); do
		hotplug_running || break
	done
}

# Handle normal 'cardctl' options (no longer supported by pccardctl):
#
while getopts "Vc:f:s:" OPT; do
	case $OPT in
		V)
			$PCCARDCTL -V
			exit $?
			;;
		c|f|s)
			# Compatibility parameters - "$OPTARG" ignored.
			;;
		*)
			usage
			;;
	esac
done
shift $[ OPTIND - 1 ]

command="$1"
socket="$2"

# Handle the command:
#
case "$command" in
	"ident"|"info"|"status")
		$PCCARDCTL $command $socket
		;;
	"config")
		echo ""
		;;
	"eject")
		cardmgr_stop "*" "${socket:-*}" "*" 2>/dev/null
		$PCCARDCTL $command $socket
		wait_hotplug_events
		;;
	"insert")
		$PCCARDCTL $command $socket
		wait_hotplug_events
		;;
	"scheme")
		echo "Sorry, scheme selection is not supported."
		exit 1
		;;
	"suspend"|"reset"|"resume")
		echo "Sorry, power management commands are not currently supported."
		exit 2
		;;
	*)
		usage
		;;
esac
