.\" @(#)bootparamd.8
.\"
.\"    $Id: bootparamd.8,v 1.1.1.1 2007/10/10 11:58:26 sergio Exp $
.\"
.Dd November 8, 1989
.Dt BOOTPARAMD 8
.Os "Linux NetKit (0.17)"
.Sh NAME
.Nm bootparamd 
.Nd boot parameter server
.Sh SYNOPSIS
.Nm rpc.bootparamd
.Op Fl d
.Op Fl s
.Op Fl r Ar router
.Op Fl f Ar file
.Sh DESCRIPTION
.Nm bootparamd
is a server process that provides information to diskless clients
necessary for booting. It consults the
.Pa /etc/bootparams
file to find the information it needs.
.Pp
This version will allow the use of aliases on the hostname in the
.Pa /etc/bootparams
file. The returned hostname to the whoami request done by the booting client
will be the name that appears in 
.Pa /etc/bootparams
and not the canonical name. In this way you can keep the answer short enough
so that machines that cannot handle long hostnames won't fail during boot.
.Sh OPTIONS
.Bl -tag -width indent
.It Fl d
Display debugging information.
.It Fl s
Log the debugging information to syslog. 
.It Fl r Ar router
The default router (a machine or an IP-address).
This defaults to the machine running the server.
.It Fl f Ar file
The file to use as boot parameter file instead of /etc/bootparams.
.Sh FILES
.Pa /etc/bootparams
.Sh BUGS
You may find the syslog loggings too verbose.
.Sh AUTHOR
Written by Klas Heggemann <klas@nada.kth.se>
