#!/bin/sh

# Build zipfiles for GLib on Win32: Separate runtime and developer ones.
# After running make install, run this.

ZIP=/tmp/glib-2.12.13.zip
DEVZIP=/tmp/glib-dev-2.12.13.zip

cd /usr/local

rm $ZIP

mkdir -p share/doc/glib-2.12.13
cp -p /home1/const/opensource/tools/glib-2.12.13/COPYING share/doc/glib-2.12.13

mkdir -p share/doc/glib-dev-2.12.13
cp -p /home1/const/opensource/tools/glib-2.12.13/COPYING share/doc/glib-dev-2.12.13

zip $ZIP -@ <<EOF
COPYING.LIB-2
bin/gspawn-win32-helper.exe
bin/gspawn-win32-helper-console.exe
bin/libglib-2.0-0.dll
bin/libgmodule-2.0-0.dll
bin/libgobject-2.0-0.dll
bin/libgthread-2.0-0.dll
EOF

zip -r $ZIP lib/locale/*/LC_MESSAGES/glib20.mo

zip -r $ZIP share/doc/glib-2.12.13

rm $DEVZIP
zip -r $DEVZIP -@ <<EOF
bin/glib-genmarshal.exe
bin/glib-gettextize
bin/glib-mkenums
bin/gobject-query.exe
include/glib-2.0
lib/libglib-2.0.dll.a
lib/glib-2.0.lib
lib/glib-2.0.def
lib/libgmodule-2.0.dll.a
lib/gmodule-2.0.lib
lib/gmodule-2.0.def
lib/libgobject-2.0.dll.a
lib/gobject-2.0.lib
lib/gobject-2.0.def
lib/libgthread-2.0.dll.a
lib/gthread-2.0.lib
lib/gthread-2.0.def
lib/glib-2.0
lib/pkgconfig/glib-2.0.pc
lib/pkgconfig/gmodule-2.0.pc
lib/pkgconfig/gmodule-no-export-2.0.pc
lib/pkgconfig/gobject-2.0.pc
lib/pkgconfig/gthread-2.0.pc
share/aclocal/glib-2.0.m4
share/aclocal/glib-gettext.m4
share/glib-2.0
share/gtk-doc/html/glib
share/gtk-doc/html/gobject
man/man1/glib-mkenums.1
man/man1/glib-genmarshal.1
EOF

zip -r $DEVZIP share/doc/glib-dev-2.12.13
