/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf,v 1.2 2002/07/18 15:37:37 dts12 Exp $
 */
#ifndef CYACS_SERIAL_SPEC_H
#define CYACS_SERIAL_SPEC_H

/*
 * function declarations 
 */
void            init_cySerialSpec(void);
FindVarMethod   var_cySerialPortTable;
WriteMethod     write_cySPort_str;
WriteMethod     write_cySPort_int;
WriteMethod     write_cySPort_ipaddr;
WriteMethod     write_cySPort_ipaddr_4_6;
WriteMethod     write_cySPortParity;
WriteMethod     write_cySPortFlowCtrl;
WriteMethod     write_cySPortAuthtype;
WriteMethod     write_cySPortProtocol;
WriteMethod     write_cySPortRemoteIP;
WriteMethod     write_cySPortRemoteIP6;
WriteMethod     write_cySPortSocketPort;
WriteMethod     write_cySPortDBmode;
WriteMethod     write_cySPortSniffSess;
WriteMethod     write_cySPortPmType;
#endif                        
