/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.create-dataset.conf,v 5.2 2002/07/17 14:41:53 dts12 Exp $
 */
#ifndef CYSERIALGROUPTABLE_H
#define CYSERIALGROUPTABLE_H

/*
 * function declarations 
 */
void init_cySerialGroupTable(void);

/*
 * column number definitions for table cySerialGroupTable 
 */
#define COLUMN_CYGROUPINDEX		1
#define COLUMN_CYGROUPNAME		2
#define COLUMN_CYGROUPUSERS		3
#endif				/* CYSERIALGROUPTABLE_H */
