#define PMCOMM_ON		"on"
#define PMCOMM_OFF		"off"
#define PMCOMM_CYCLE		"cycle"
#define PMCOMM_LOCK		"lock"
#define PMCOMM_UNLOCK		"unlock"
#define PMCOMM_STATUS		"status"
#define PMCOMM_CURRENT		"current"
#define	PMCOMM_TEMPERATURE	"temperature"
#define PMCOMM_SYSLOG		"syslog"
#define PMCOMM_BUZZER		"buzzer"
#define PMCOMM_CURRPROTECTION	"currentprotection"
#define PMCOMM_REBOOTDURATION	NULL
#define PMCOMM_POWERONDELAY	NULL
#define PMCOMM_POWEROFFDELAY	NULL

#define PM_LOCKED		0
#define PM_UNLOCKED		1
#define PM_ON			0
#define PM_OFF			1
